config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :users, only: :show
  resources :prototypes do
    resources :likes, only: [:create, :destroy]
  end
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  belongs_to :prototype
  mount_uploader :thumbnail, CapturedImageUploader
  enum status: %i(main sub)
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: :like_count
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  has_many :captured_images
  has_many :likes
  belongs_to :user
  accepts_nested_attributes_for :captured_images

  def like_user(user)
   likes.find_by(user_id: user.id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_many :prototypes
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:avatar, :name, :works, :member, :profile)
    devise_parameter_sanitizer.for(:account_update).push(:avatar, :name, :works, :member, :profile)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_like_prototype
  def create
    @like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
  end

  def destroy
    @like = current_user.likes.find_by(prototype_id: params[:prototype_id])
    @like.destroy
    @likes = Like.where(prototype_id: params[:prototype_id])
  end

  def set_like_prototype
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController

  before_action :set_prototype ,only: [:show, :edit, :destroy, :update]
  def index
    @prototypes = Prototype.all
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
  end

  def create
    Prototype.create(prototype_params)
    redirect_to action: :index
  end

  def show
    @likes = Like.where(prototype_id: params[:id])
    @like = @likes.where(user_id: current_user.id).first_or_initialize
  end

  def edit
    @prototype.captured_images.build
  end

  def destroy
    @prototype.destroy
    redirect_to action: :index
  end

  def update
    @prototype.update(prototype_params)
    redirect_to action: :index
  end

  private
  def prototype_params
    params.require(:prototype).permit(
        :title,
        :catch_copy,
        :concept,
        captured_images_attributes: [
        :thumbnail,
        :status,
        :id
        ]
      ).merge(user_id: current_user.id)
  end

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @prototypes = current_user.prototypes
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_main_thumbnail(prototype)
    prototype.captured_images.main.first.thumbnail
  end
end

app/helpers/prototype_helper.rb
module PrototypeHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
  
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    =link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"),root_path,class: 'navbar-brand'
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", href:"#", role:"button"}
              = current_user.name
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to("My Page", user_path(current_user))
              %li
                = link_to("Profile Edit", edit_user_registration_path)
              %li
                = link_to("Logout", destroy_user_session_path , method: :delete)
          %li
            .btn.btn-primary.navbar-btn
              = link_to("New Proto", new_prototype_path(@prototype))
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to("Get Started",new_user_session_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = yield
    = render "layouts/footer"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if @prototype.like_user(current_user)
    = link_to prototype_like_path(@prototype,@like), method: :delete, remote: true do
      %button.btn.btn-default#like-button
        = image_tag("icon_heart.svg",style: "width: 64px; height: 64px;")
        Like
        %span.num
          = @prototype.like_count
  - else
    = form_for [@prototype,@like], remote: true do |f|
      %button.btn.btn-default#like-button
        = f.submit "Like", type: "hidden"
        = image_tag("icon_heart.svg",style: "width: 64px; height: 64px;")
        Like
        %span.num
          = @prototype.like_count
- else
  %button.btn.btn-default#like-button
    = image_tag("",style: "width: 64px; height: 64px;")
    Like
    %span.num
      = @prototype.like_count

app/views/likes/create.js.erb
$(".col-md-6.text-right").html("<%= j(render partial: 'likes/like') %>")

app/views/likes/destroy.js.erb
$(".col-md-6.text-right").html("<%= j(render partial: 'likes/like') %>");

app/views/prototype/new.html.haml
%form.container.proto-new{:action => ""}
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        %input.proto-new-title{:type => "text", :placeholder => "Title"}/
    .row
      .col-md-12
        .cover-image-upload
          %input{:type => "file"}/
      .col-md-12
        %ul.proto-sub-list.list-group
          %li.list-group-item.col-md-4
            .image-upload
              %input{:type => "file"}/
          %li.list-group-item.col-md-4
            .image-upload
              %input{:type => "file"}/
          %li.list-group-item.col-md-4
            .image-upload-plus
              %span +
    .row.proto-description
      .col-md-12
        %input{:type => "text", :placeholder => "Catch Copy"}/
      .col-md-12
        %textarea{:name => "", :cols => "30", :rows => "4", :placeholder => "Concept"}
      .col-md-12
        %h4 Tag List
        .row
          .col-md-3
            %input{:type => "text", :placeholder => "Web Design"}/
          .col-md-3
            %input{:type => "text", :placeholder => "UI"}/
          .col-md-3
            %input{:type => "text", :placeholder => "Application"}/
    .row.text-center.proto-btn
      %button.btn.btn-lg.btn-primary.btn-block{:type => "submit"} Publish
      

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to image_tag(set_main_thumbnail(prototype)),prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          =link_to "#{prototype.user.name}",user_path(prototype.user)
        .proto-posted
          = prototype.created_at
      %ul.proto-tag-list.list-inline
        -# タグはあとで実装するので今は無視
        %li
          %a{href: "#", class: "btn btn-default"} iPad
        %li
          %a{href: "#", class: "btn btn-default"} wireframe

app/views/prototypes/edit.html.haml
.container.proto-new
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        = form_for (@prototype) do |f|
          = f.label :Title
          %br
          = f.text_field :title, autofocus: true, required: true, placeholder:"Title", class: "proto-new-title"
          .row
            .col-md-12
              .cover-image-uploader
                = f.label :MainThumbnail
                %br
                = f.fields_for :captured_images, (@prototype.captured_images.main) do |captured_image|
                  -# ここにshowの画像タグをはるd
                  = captured_image.file_field :thumbnail, required: true
                  = captured_image.hidden_field :status, value: "main"
              %br
              = f.label :Subthumbnails
              %ul.proto-sub-list.list-group
                = f.fields_for :captured_images, (@prototype.captured_images.sub) do |captured_image|
                  %li.list-group-item.col-md-4
                    = captured_image.file_field :thumbnail, class:"image-uploader"
                    = captured_image.hidden_field :status, value: "sub"
          .row.proto-description
            .col-md-12
              =f.label :Catch_Copy
              =f.text_field :catch_copy,required: true
            .col-md-12
              =f.label :Concept
              =f.text_area :concept,required: true
            .col-md-12
              %h4 Tag List
              -# タグはまだ実装前なので未修正
              .row
                .col-md-3
                  %input{type: "text", placeholder: "Web Design"}/
                .col-md-3
                  %input{type: "text", placeholder: "UI"}/
                .col-md-3
                  %input{type: "text", placeholder: "Application"}/
          .row.text-center.proto-btn
            = f.submit "Publish", class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      -# タグ機能のときに実装すること
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          %a{href: "#"} Popular PROTO
        %li{role: "presentation"}
          %a{href: "#"} Newest PROTO
      %button{type: "button", class: "btn btn-default col-lg-1"} View Tags

.container.proto-list
  .row
    = render @prototypes

.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label" => "Previous", :href => "#"}
        %span{"aria-hidden" => "true"} «
    %li.active
      %a{href: "#"}
        1
        %span.sr-only (current)
    %li
      %a{href: "#"} 2
    %li
      %a{href: "#"} 3
    %li
      %a{href: "#"} 4
    %li
      %a{href: "#"} 5
    %li
      %a{"aria-label" => "Next", href:"#"}
        %span{"aria-hidden" => "true"} »

app/views/prototypes/new.html.haml
.container.proto-new
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-md-12
        = form_for (@prototype) do |f|
          = f.label :Title
          %br
          = f.text_field :title, autofocus: true, required: true, placeholder:"Title", class: "proto-new-title"
          .row
            .col-md-12
              .cover-image-uploader
                = f.label :MainThumbnail
                %br
                = f.fields_for :captured_images do |captured_image|
                  = captured_image.file_field :thumbnail, required: true
                  = captured_image.hidden_field :status, value: "main"
              %br
              = f.label :Subthumbnails
              %ul.proto-sub-list.list-group
                = f.fields_for :captured_images do |captured_image|
                  -# ここはJSで後で実装をする
                  %li.list-group-item.col-md-4
                    = captured_image.file_field :thumbnail, class:"image-uploader"
                    = captured_image.hidden_field :status, value: "sub"
          .row.proto-description
            .col-md-12
              =f.label :Catch_Copy
              =f.text_field :catch_copy,required: true
            .col-md-12
              =f.label :Concept
              =f.text_area :concept,required: true
            .col-md-12
              %h4 Tag List
              -# タグはまだ実装前なので未修正
              .row
                .col-md-3
                  %input{type: "text", placeholder: "Web Design"}/
                .col-md-3
                  %input{type: "text", placeholder: "UI"}/
                .col-md-3
                  %input{type: "text", placeholder: "Application"}/
          .row.text-center.proto-btn
            = f.submit "Publish", class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          =link_to image_tag(@prototype.user.avatar,alt: "64x64",style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
          = @prototype.title
          .proto-user
            =link_to "#{@prototype.user.name}",user_path
            %span.degree
              = @prototype.user.member
            - if user_signed_in? && current_user.id == @prototype.user_id
              %span.degree
                = link_to("Edit", edit_prototype_path(@prototype.id))
              %span.degree
                = link_to("Delete", prototype_path(@prototype.id), method: :delete)
    .col-md-6.text-right
      = render partial: "likes/like"
  .row
    .col-md-9
      = image_tag(set_main_thumbnail(@prototype), class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |sub|
          %li.list-group-item
            = image_tag(sub.thumbnail, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      -# タグ機能のときに書き換えを行う
      %ul.proto-tag-list.list-inline
        %li
          %a{href: "#", class: "btn btn-default"} iPad
        %li
          %a{href: "#", class: "btn btn-default"} wireframe
  .row.proto-comments
    %h4.col-md-12
      Comments
      -# 以下はコメント機能の実装で書き換えを行う
      %span.num (10)
    .col-md-8
      .media
        .media-left
          %a{href: "#"}
            %img.media-object{alt: "64x64", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", style: "width: 64px; height: 64px;"}/
        .media-body
          %h4#top-aligned-media.media-heading
            Top aligned media
            %a.anchorjs-link{href: "#top-aligned-media"}
              %span.anchorjs-icon
          %p Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          %p Donec sed odio dui. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          %p Donec sed odio dui. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
      %form.form-inline{role: "form"}
        %h4 Write a comment
        .row
          .form-group.col-md-10
            %textarea.form-control{placeholder: "Your comments", rows: "3"}
          .form-group.col-md-2
            %button.btn.btn-primary Comment

app/views/top/index.html.haml
.jumbotron
  .container.text-center
    = image_tag "header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px"

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{:role => "presentation"}
          = link_to "Popular PROTO", href:"#"
        %li{:role => "presentation"}
          %a{:href => "#"} Newest PROTO
      %button{:type => "button", :class => "btn btn-default col-lg-1"} View Tags

.container.proto-list
  .row
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{:href => "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li
                %a{:href => "#", :class => "btn btn-default"} wireframe
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{:href => "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li
                %a{:href => "#", :class => "btn btn-default"} wireframe

    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{:href => "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li
                %a{:href => "#", :class => "btn btn-default"} wireframe

    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{:href => "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li
                %a{:href => "#", :class => "btn btn-default"} wireframe

    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{:href => "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li
                %a{:href => "#", :class => "btn btn-default"} wireframe

    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{:href => "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li
                %a{:href => "#", :class => "btn btn-default"} wireframe

    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{:href => "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li
                %a{:href => "#", :class => "btn btn-default"} wireframe

    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{:href => ""}
          = image_tag("sample.png")
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-user
                %a{:href => "#"} by user
              .proto-posted
                Apr 26
            %ul.proto-tag-list.list-inline
              %li
                %a{:href => "#", :class => "btn btn-default"} iPad
              %li
                %a{:href => "#", :class => "btn btn-default"} wireframe

.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label" => "Previous", :href => "#"}
        %span{"aria-hidden" => "true"} «
    %li.active
      %a{:href => "#"}
        1
        %span.sr-only (current)
    %li
      %a{:href => "#"} 2
    %li
      %a{:href => "#"} 3
    %li
      %a{:href => "#"} 4
    %li
      %a{:href => "#"} 5
    %li
      %a{"aria-label" => "Next", :href => "#"}
        %span{"aria-hidden" => "true"} »

app/views/users/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
   = link_to image_tag(set_main_thumbnail(user_prototype)), prototype_path(user_prototype)
    .caption
      %h3
        = user_prototype.title
      .proto-meta
        .proto-date
          = user_prototype.created_ats
      %ul.proto-tag-list.list-inline
        %li
          %a{:href => "#", :class => "btn btn-default"} iPad
        %li
          %a{:href => "#", :class => "btn btn-default"} wireframe

app/views/users/_user_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
   = link_to image_tag(set_main_thumnail(user_prototype)), prototype_path(user_prototype)
    .caption
      %h3
        = user_prototype.title
      .proto-meta
        .proto-date
          = user_prototype.created_ats
      %ul.proto-tag-list.list-inline
        %li
          %a{:href => "#", :class => "btn btn-default"} iPad
        %li
          %a{:href => "#", :class => "btn btn-default"} wireframe

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = link_to image_tag("#{current_user.avatar}",alt: "avatar",size:"64x64",class:"media-object"),"#"
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree
            = current_user.member
        .row
          .col-md-6
            %h4 Profile
            = current_user.profile
          .col-md-6
            %h4 Works
            = current_user.works
  .row
    = render @prototypes

.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label" => "Previous", :href => "#"}
        %span{"aria-hidden" => "true"} «
    %li.active
      %a{:href => "#"}
        1
        %span.sr-only (current)
    %li
      %a{"aria-label" => "Next", :href => "#"}
        %span{"aria-hidden" => "true"} »